/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(main)'}/concierge` | `/concierge`; params?: Router.UnknownInputParams; } | { pathname: `${'/(main)'}/explore` | `/explore`; params?: Router.UnknownInputParams; } | { pathname: `${'/(main)'}/more` | `/more`; params?: Router.UnknownInputParams; } | { pathname: `${'/(main)'}/pass` | `/pass`; params?: Router.UnknownInputParams; } | { pathname: `${'/(main)'}/places` | `/places`; params?: Router.UnknownInputParams; } | { pathname: `/onboarding/country-select`; params?: Router.UnknownInputParams; } | { pathname: `/onboarding/splash`; params?: Router.UnknownInputParams; } | { pathname: `/onboarding/welcome`; params?: Router.UnknownInputParams; };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(main)'}/concierge` | `/concierge`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(main)'}/explore` | `/explore`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(main)'}/more` | `/more`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(main)'}/pass` | `/pass`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(main)'}/places` | `/places`; params?: Router.UnknownOutputParams; } | { pathname: `/onboarding/country-select`; params?: Router.UnknownOutputParams; } | { pathname: `/onboarding/splash`; params?: Router.UnknownOutputParams; } | { pathname: `/onboarding/welcome`; params?: Router.UnknownOutputParams; };
      href: Router.RelativePathString | Router.ExternalPathString | `/${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `${'/(main)'}/concierge${`?${string}` | `#${string}` | ''}` | `/concierge${`?${string}` | `#${string}` | ''}` | `${'/(main)'}/explore${`?${string}` | `#${string}` | ''}` | `/explore${`?${string}` | `#${string}` | ''}` | `${'/(main)'}/more${`?${string}` | `#${string}` | ''}` | `/more${`?${string}` | `#${string}` | ''}` | `${'/(main)'}/pass${`?${string}` | `#${string}` | ''}` | `/pass${`?${string}` | `#${string}` | ''}` | `${'/(main)'}/places${`?${string}` | `#${string}` | ''}` | `/places${`?${string}` | `#${string}` | ''}` | `/onboarding/country-select${`?${string}` | `#${string}` | ''}` | `/onboarding/splash${`?${string}` | `#${string}` | ''}` | `/onboarding/welcome${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(main)'}/concierge` | `/concierge`; params?: Router.UnknownInputParams; } | { pathname: `${'/(main)'}/explore` | `/explore`; params?: Router.UnknownInputParams; } | { pathname: `${'/(main)'}/more` | `/more`; params?: Router.UnknownInputParams; } | { pathname: `${'/(main)'}/pass` | `/pass`; params?: Router.UnknownInputParams; } | { pathname: `${'/(main)'}/places` | `/places`; params?: Router.UnknownInputParams; } | { pathname: `/onboarding/country-select`; params?: Router.UnknownInputParams; } | { pathname: `/onboarding/splash`; params?: Router.UnknownInputParams; } | { pathname: `/onboarding/welcome`; params?: Router.UnknownInputParams; };
    }
  }
}
